version: "3.7"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: paradox
      POSTGRES_USER: zeno
      POSTGRES_DB: foodb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: node:alpine
    depends_on:
      - db
    ports:
      - "4000:4000"